name: 豆瓣海报自动更新

# 新增：添加权限配置，解决git操作权限不足
permissions:
  contents: write  # 允许读写仓库内容
  pages: write     # 允许部署GitHub Pages
  id-token: write  # 用于身份验证

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 禁用默认凭据，使用新权限

      - name: 配置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 安装依赖库
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 爬取豆瓣海报
        env:
          DOUBAN_COLLECT_URL: ${{ secrets.DOUBAN_COLLECT_URL }}
          DOUBAN_COOKIE: ${{ secrets.DOUBAN_COOKIE }}
        run: python douban_spider.py

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
          # 新增：明确权限
          enable_jekyll: false
