name: 爬取豆瓣海报

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 拉取代码时使用新的 Token 名称
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行爬虫
        env:
          DOUBAN_COLLECT_URL: ${{ secrets.DOUBAN_COLLECT_URL }}
          DOUBAN_WISH_URL: ${{ secrets.DOUBAN_WISH_URL }}
          DOUBAN_COOKIE: ${{ secrets.DOUBAN_COOKIE }}  # 可选
        run: python douban_spider.py

      - name: 提交更新
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase
          git add posters/ poster_paths.json
          git commit -m "自动更新海报（$(date +'%Y-%m-%d')）" || echo "无更新"
          git push origin main
        env:
          # 推送代码时使用新的 Token 名称
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
